name: Build

on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11.1"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow

      - name: Create ArangoDB Docker container
        run: >
          docker create --name arango -p 8529:8529 -e ARANGO_ROOT_PASSWORD=passwd
          arangodb/arangodb:3.7.7 --server.jwt-secret-keyfile=/tmp/keyfile

      - name: Copy Foxx service zip into ArangoDB Docker container
        run: docker cp tests/static/service.zip arango:/tmp/service.zip

      - name: Copy keyfile into ArangoDB Docker container
        run: docker cp tests/static/keyfile arango:/tmp/keyfile

      - name: Start ArangoDB Docker container
        run: docker start arango

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Debug with tmate
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0

      - name: Install dependencies
        run: pip install .[dev]

      - name: Run unit tests
        run: py.test --complete --cov=arango --cov-report=xml

      - name: Run Sphinx doctest
        run: python -m sphinx -b doctest docs docs/_build

      - name: Generate Sphinx HTML
        run: python -m sphinx -b html -W docs docs/_build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.python-version == '3.10'
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
